// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9YpP1DUrrkTfT05UvpnPeZLbVnOsrNtw',
    appId: '1:370258069928:web:bcb34bb9490045df48359d',
    messagingSenderId: '370258069928',
    projectId: 'messge-ea34f',
    authDomain: 'messge-ea34f.firebaseapp.com',
    databaseURL: 'https://messge-ea34f-default-rtdb.firebaseio.com',
    storageBucket: 'messge-ea34f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChLVB0HYHlwfc8TV8OkBVxkRXEaIE96_o',
    appId: '1:370258069928:android:dbf17aed4cb432c848359d',
    messagingSenderId: '370258069928',
    projectId: 'messge-ea34f',
    databaseURL: 'https://messge-ea34f-default-rtdb.firebaseio.com',
    storageBucket: 'messge-ea34f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQmH2pTA0MfZNfmdUMMU_qFYRl0kfHMIs',
    appId: '1:370258069928:ios:346468753d93dfbd48359d',
    messagingSenderId: '370258069928',
    projectId: 'messge-ea34f',
    databaseURL: 'https://messge-ea34f-default-rtdb.firebaseio.com',
    storageBucket: 'messge-ea34f.firebasestorage.app',
    iosBundleId: 'com.example.unibook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQmH2pTA0MfZNfmdUMMU_qFYRl0kfHMIs',
    appId: '1:370258069928:ios:346468753d93dfbd48359d',
    messagingSenderId: '370258069928',
    projectId: 'messge-ea34f',
    databaseURL: 'https://messge-ea34f-default-rtdb.firebaseio.com',
    storageBucket: 'messge-ea34f.firebasestorage.app',
    iosBundleId: 'com.example.unibook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9YpP1DUrrkTfT05UvpnPeZLbVnOsrNtw',
    appId: '1:370258069928:web:ea14154914c33c7b48359d',
    messagingSenderId: '370258069928',
    projectId: 'messge-ea34f',
    authDomain: 'messge-ea34f.firebaseapp.com',
    databaseURL: 'https://messge-ea34f-default-rtdb.firebaseio.com',
    storageBucket: 'messge-ea34f.firebasestorage.app',
  );
}
